---
booktitle: 'Proceedings of IndabaX Nigeria 2026: Building Scalable AI That Works:
  From Research to Deployment in Resource-Constrained Environments'
shortname: IndabaXNG
volume: '319'
year: '2026'
start: &1 2026-05-11
end: 2026-05-14
published: 2026-06-22
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: IndabaXNigeria-2026
month: 0
cycles: false
bibtex_editor: Folorunso, Sakinat and Ogundokun, Roseline and Oladipo, Francisca
editor:
- given: Sakinat
  family: Folorunso
- given: Roseline
  family: Ogundokun
- given: Francisca
  family: Oladipo
title: Proceedings of Machine Learning Research
description: |
  Proceedings of IndabaX Nigeria 2026: Building Scalable AI That Works: From Research to Deployment in Resource-Constrained Environments
    Held in University of Ibadan, Ibadan, Nigeria on 11-14 May 2026

  Published as Volume 319 by the Proceedings of Machine Learning Research on 22 June 2026.

  Volume Edited by:
    Sakinat Folorunso
    Roseline Ogundokun
    Francisca Oladipo

  Series Editors:
    Neil D. Lawrence
date_str: 11--14 May
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v319"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v319
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v319
email: ''
conference:
  name: IndabaX Nigeria Conference
  url: https://indabaxng.github.io/
  location: University of Ibadan, Ibadan, Nigeria
  dates:
  - *1
  - 2026-05-12
  - 2026-05-13
  - 2026-05-14
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: indabax26_clean.bib
# Site settings
# Original source:  indabax26_clean.bib
